### ISSUE TITLE
circus is actually unusable :\

### ISSUE THREAD

**Issue by idchlife** [circus-tent/circus#1069]
I started using it on Ubuntu server and stumbled upon same problems I encountered on Mac OS

circusctl tells everytime about timeout.
circus-top shows dash line and that's all
circusd without --daemon is the only case when it's working but... It's actually more hussle than by hand running gunicorn + other processes, because killing when circusd stopped in terminal session is "ps ax grep and kill", since circusctl always gives timeout.

**Comment by zogzog** [comment]
Don't forget to specify the --endpoint if you didn't use the default one.

**Comment by idchlife** [comment]
> Don't forget to specify the --endpoint if you didn't use the default one.

you mean circus is working now? I thought project was abandoned long ago.

**Comment by thedrow** [comment]
It still releases new versions and accepts contributions so 🤷‍♂

**Comment by zogzog** [comment]
To be fair it is stuck on old versions of tornado and other things, which is becoming annoying as time passes.
I've taken a couple hours investigating the cost of an upgrade but it is not easy. Needs to be acquainted with async + tornado stuff.

**Comment by idchlife** [comment]
Anyway, I don't use circus and don't intend to do so in the near future, so I suspect this issue should be closed (it almost 2 years old). I don't know whether problems I had were resolved but I suspect (since there happens to be activity in this repo) circus is working now or something.

Thanks!

**Comment by sphuber** [comment]
I am using `circus` in an active project and would like to see it continue its life. Therefore I recently restored the CI and then upgraded the code to support latest version of PyZMQ which was also causing dependency issues. The main problem remaining is indeed the tornado configuration it would be nice to get this fixed. I have also looked into this and might be able to fix it in the near future.
